- hosts: mysql
  tasks:
  - name: Configuring Docker Repository
    yum_repository:
      description: DOCKER YUM repo
      name: docker
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
      gpgcheck: no
      state: present
    become: yes
  - name: Installing Docker
    package:
      name: docker-ce-18.09.1-3.el7.x86_64
      skip_broken: yes
      state: present
    become: yes
  - name: Start Docker Serivce
    service:
      name: docker
      state: started
    become: yes
  - name: Install Python
    package: 
      name: python3
      state: present
    become: yes
  - name: Install Pip3
    package: 
      name: python3-pip
      state: present  
    become: yes
  - name: Install docker pip package
    command: pip3 install docker
    become: yes
  - name: MySQL Docker Container
    docker_container:
      name: mysql
      image: mysql:5.7
      detach: yes
      pull: yes
      env:
        MYSQL_ROOT_PASSWORD: rootpass
        MYSQL_USER: siva
        MYSQL_PASSWORD: sivanaik
      exposed_ports:
      - "3306"
      ports:
      - "3306:3306"
    become: yes