- hosts: localhost
  tasks:
  - name: Configuring Docker Repository
    yum_repository:
      description: DOCKER YUM repo
      name: docker
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
      gpgcheck: no
      state: present
    become: yes
  - name: Installing Docker
    package:
      name: docker-ce-18.09.1-3.el7.x86_64
      skip_broken: yes
      state: present
    become: yes
  - name: Start Docker Serivce
    service:
      name: docker
      state: started
    become: yes
  - name: Install docker pip package
    command: pip3 install docker
    become: yes
  - name: WordPress Docker Container
    docker_container:
      name: wordpress
      image: wordpress:5.1.1-php7.3-apache
      detach: yes
      pull: yes
      exposed_ports:
      - "80"
      ports:
      - "80:80"
    become: yes